# SITE CONFIGURATION
baseurl: "/nesp"
url: "https://christina-ladam.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Nevada Election Survey Project                                    # site's title
description: "The Nevada Election Study Project (NESP), run by political scientists at the University of Nevada, Reno, conducts surveys of Nevadans on their political and policy views."      # used by search engines
avatar: assets/img/nlogo.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: The Nevada Election Study Project (NESP) conducts surveys of Nevadans on their political and policy views.  # Change Blog header text
header_feature_image: assets/img/capitol-resize.PNG
header_feature_image_responsive: false
footer_text: ""

# Blog
excerpt: true                                         # Or "truncate" (first 250 characters), "false" to disable
post_navigation: false
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: false
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-relative-links]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github

relative_links:
  enabled:     true
  collections: true
